


POST https://api-stores.storeino.world/api/themes/update?id=616ff0c2fe0f550b9b6a5822
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2MTQ0NDkxNzllNmFkNjA0YTYyODc2ZTAiLCJuYW1lIjoidGVjaG5vIiwic3ViZG9tYWluIjoidGVjaG5vLnN0b3JlaW5vLndvcmxkIn0sInVzZXIiOnsiX2lkIjoiNjA0MGU0OGYyMzY0NzYwYTMyZWUyNTFiIiwiZmlyc3RuYW1lIjoiYWJkZXJyYWhpbSIsImxhc3RuYW1lIjoib3VraHJpYiJ9LCJjb21wYW55Ijp7Il9pZCI6IjYwNDBlNDhmMjM2NDc2MGEzMmVlMjUxOSIsIm5hbWUiOiJva2F5c3MiLCJzdGF0dXMiOiJVTkNPTVBMRVRFRCJ9LCJpYXQiOjE2MzQ3MjUyOTYsImV4cCI6MTYzNTU4OTI5Nn0.0Xl56D1Vk2j89kOB2DO64DT99BSTDysGtSuQkhxXROo

{
    "team": {
        "_id": "5f21374a175b5e8e309be827",
        "name": "Storeino Team",
        "url": "https://market.storeino.com/storeino/"
    },
    "config": {
        "schema": {
            "fields": {
                "products": [],
                "collections": [],
                "images": [],
                "menus": [],
                "pages": [],
                "brands": []
            },
            "ids": {
                "collections": [],
                "products": [],
                "images": [],
                "menus": [],
                "pages": [],
                "brands": []
            }
        },
        "settings": {
            "tabs": [
                {
                    "name": "global_options",
                    "sections": [
                        {
                            "name": "colors",
                            "icon": "select_all",
                            "blocks": [
                                {
                                    "name": "global",
                                    "values": [
                                        {
                                            "name": "primary_color",
                                            "note": "your_website_primary_color",
                                            "path": "style.primary_color",
                                            "type": "tc_color",
                                            "value": "#00825a"
                                        }
                                    ]
                                        
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "global_sections",
                    "sections": [
                        {
                            "name": "header",
                            "icon": "select_all",
                            "blocks": [
                                {
                                    "name": "header",
                                    "values": [
                                        {
                                            "name": "header_logo",
                                            "note": "your_website_header_logo",
                                            "path": "sections.header.logo",
                                            "type": "tc_image",
                                            "value": null
                                        }
                                    ]
                                },
                                {
                                    "name": "menu",
                                    "values": [
                                        {
                                            "name": "header_menu",
                                            "note": "your_website_header_menu",
                                            "path": "sections.header.menu",
                                            "type": "tc_menu",
                                            "value": null
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "home_sections",
                    "sections": [
                        {
                            "name": "banner",
                            "icon": "select_all",
                            "pushable": true,
                            "default": {
                                "name": "items[9]",
                                "values": [
                                    {
                                        "name": "banner_image",
                                        "path": "sections.banner.items.item_9.image",
                                        "type": "tc_image",
                                        "value": null
                                    },
                                    {
                                        "name": "banner_title",
                                        "path": "sections.banner.items.item_9.title",
                                        "type": "tc_input",
                                        "value": "Default title"
                                    },
                                    {
                                        "name": "banner_description",
                                        "path": "sections.banner.items.item_9.description",
                                        "type": "tc_input",
                                        "value": "Default description"
                                    },
                                    {
                                        "name": "banner_show_button",
                                        "path": "sections.banner.items.item_9.button.active",
                                        "type": "tc_checkbox",
                                        "value": false
                                    },
                                    {
                                        "name": "banner_button_text",
                                        "path": "sections.banner.items.item_9.button.text",
                                        "type": "tc_input",
                                        "value": "Shop now"
                                    },
                                    {
                                        "name": "banner_button_url",
                                        "path": "sections.banner.items.item_9.button.url",
                                        "type": "tc_input",
                                        "value": "/shop"
                                    }
                                ]
                            },
                            "blocks":[]
                        }
                    ]
                }
            ]
        },
        "current": {
            "style": {
                "primary_color": "#00825a"
            },
            "sections": {
                "header": {
                    "logo": null,
                    "menu": null
                },
                "banner": {
                    "items": {
                        "item_0": 
                        { 
                            "image": null,
                            "title": "Renal & Urology Nutrition News, Diet Tips",
                            "description": "Greater consumption of healthful plant-based foods is associated with significantly reduced risks for advanced, lethal, and fatal prostate cancer, especially among men younger than 65 years",
                            "button": {
                                "active": true,
                                "url": "/shop",
                                "text": "Order now"
                            }
                        },
                        "item_1": { 
                            "image": null,
                            "title": "Renal & Urology Nutrition News, Diet Tips",
                            "description": "Greater consumption of healthful plant-based foods is associated with significantly reduced risks for advanced, lethal, and fatal prostate cancer, especially among men younger than 65 years",
                            "button": {
                                "active": true,
                                "url": "/shop",
                                "text": "Order now"
                            }
                        }
                    },
                    "right": {
                        "image": null,
                        "url": "/shop"
                    }
                },
                "collections": {},
                "products": {},
                "product": {
                    "share_buttons": {
                        "whatsapp": true,
                        "facebook": true,
                        "twitter": true,
                        "linkedin": true
                    }
                },
                "posts": {},
                "post": {
                    "share_buttons": {
                        "whatsapp": true,
                        "facebook": true,
                        "twitter": true,
                        "linkedin": true
                    }
                },
                "services": {},
                "footer": {
                    "about": "<h3>Experience Moroccofresh - for agriculture.</h3> <p> Whether you are a livestock farmer or a farmer, a contractor or a forester: In the BayWa portal you will find a wide range of animal feed, seeds and crop protection - conventional or ecological - for agriculture. In addition, you will receive detailed information about our diverse advisory services, services, events and topics as well as about us, your BayWa. <br>Discover our diversity - digitally and on site </p>",
                    "methods": {
                        "visa": true,
                        "mastercard": true,
                        "transfer": true,
                        "cash": true
                    },
                    "social_media": {
                        "facebook": "https://www.facebook.com/",
                        "twitter": "https://twitter.com/",
                        "instagram": "https://www.instagram.com/",
                        "youtube": "https://www.youtube.com/",
                        "linkedin": "https://www.linkedin.com/",
                        "whatsapp": "https://web.whatsapp.com/",
                        "snapchat": "https://www.snapchat.com/",
                        "tiktok": "https://www.tiktok.com/"
                    },
                    "menu": null
                }
            },
            "translates": []
        }
    },
    "images": [
        "https://cdn.dribbble.com/users/1983741/screenshots/10636148/media/c537c929947ebff9ad38dc6bc9ede9bb.jpg?compress=1&resize=400x300"
    ],
    "isActive": true,
    "autoRenew": false,
    "expiryDate": "2050-12-12T00:00:00.000Z",
    "name": "palest",
    "url": "/themes/palest",
    "route": "palest",
    "defaults": [],
    "paymentType": "yearly",
    "payments": [],
    "price": 22,
    "description": "✔ Simple and easy theme to use ✔ Well presented and convertible store and product page ✔ SEO optimized ✔ Responsive to all devices",
    "publicName": "Palest - Multipurpose Responsive E-commerce Template"
}