


POST https://api-stores.storeino.com/api/themes/update?id=615345112d03a91d188a169c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2MTFkNzAyZTIzZGU1NzFmYjliOTdkOTQiLCJuYW1lIjoidGVjaG5vIiwic3ViZG9tYWluIjoidGVjaG5vLnN0b3JlaW5vLmNvbSJ9LCJ1c2VyIjp7Il9pZCI6IjVmZGI4MjE1ODA5NWRiMDBkNzc4MDg4NiIsImZpcnN0bmFtZSI6InN0b3JlaW5vIiwibGFzdG5hbWUiOiJkZXZlbG9wZXIifSwiY29tcGFueSI6eyJfaWQiOiI1ZmRiODIxNTgwOTVkYjAwZDc3ODA4ODQiLCJuYW1lIjoiU1RPUkVJTk8gU1lTVEVNIiwic3RhdHVzIjoiYWN0aXZlIn0sImlhdCI6MTYzMjg0NjMwNywiZXhwIjoxNjY0MzgyMzA3fQ.Lvhle9Gu0P67npW5Fvnq_3YYT7dzDFaMbRPqi7HbeAE

{
    "team": {
        "_id": "5f21374a175b5e8e309be827",
        "name": "Storeino Team",
        "url": "https://market.storeino.com/storeino/"
    },
    "config": {
        "schema": {
            "fields": {
                "products": [],
                "collections": [],
                "images": [],
                "menus": [],
                "pages": [],
                "brands": []
            },
            "ids": {
                "collections": [],
                "products": [],
                "images": ["611d8553af093e19cef7e21c", "611d7a4eaf093e19cef7dbce", "615b20f62d03a91d18935093", "615b20f42d03a91d18935092"],
                "menus": ["6152f5462d03a91d18898c6c"],
                "pages": [],
                "brands": []
            }
        },
        "settings": {
            "tabs": []
        },
        "current": {
            "style": {
                "primary_color": "#00825a"
            },
            "sections": {
                "header": {
                    "logo": "611d8553af093e19cef7e21c",
                    "menu": "6152f5462d03a91d18898c6c"
                },
                "banner": {
                    "items": [
                        { 
                            "image": "615b20f62d03a91d18935093",
                            "title": "Renal & Urology Nutrition News, Diet Tips",
                            "description": "Greater consumption of healthful plant-based foods is associated with significantly reduced risks for advanced, lethal, and fatal prostate cancer, especially among men younger than 65 years",
                            "button": {
                                "active": true,
                                "url": "/shop",
                                "text": "Order now"
                            }
                        },
                        { 
                            "image": "615b20f42d03a91d18935092",
                            "title": "Renal & Urology Nutrition News, Diet Tips",
                            "description": "Greater consumption of healthful plant-based foods is associated with significantly reduced risks for advanced, lethal, and fatal prostate cancer, especially among men younger than 65 years",
                            "button": {
                                "active": true,
                                "url": "/shop",
                                "text": "Order now"
                            }
                        }
                    ],
                    "right": {
                        "image": "611d7a4eaf093e19cef7dbce",
                        "url": "/shop"
                    }
                },
                "collections": {},
                "products": {},
                "posts": {},
                "services": {},
                "footer": {
                    "about": "<h3>Experience Moroccofresh - for agriculture.</h3> <p> Whether you are a livestock farmer or a farmer, a contractor or a forester: In the BayWa portal you will find a wide range of animal feed, seeds and crop protection - conventional or ecological - for agriculture. In addition, you will receive detailed information about our diverse advisory services, services, events and topics as well as about us, your BayWa. <br>Discover our diversity - digitally and on site </p>",
                    "methods": {
                        "visa": true,
                        "mastercard": true,
                        "transfer": true,
                        "cash": true
                    },
                    "socialMedia": {
                        "facebook": "https://www.facebook.com/",
                        "twitter": "https://twitter.com/",
                        "instagram": "https://www.instagram.com/",
                        "youtube": "https://www.youtube.com/",
                        "linkedin": "https://www.linkedin.com/"
                    },
                    "menu": "6152f5462d03a91d18898c6c"
                }
            },
            "translates": []
        }
    },
    "images": [
        "https://cdn.dribbble.com/users/1983741/screenshots/10636148/media/c537c929947ebff9ad38dc6bc9ede9bb.jpg?compress=1&resize=400x300"
    ],
    "isActive": true,
    "autoRenew": false,
    "expiryDate": "2050-12-12T00:00:00.000Z",
    "name": "default",
    "url": "/themes/palest",
    "route": "palest",
    "defaults": [],
    "paymentType": "yearly",
    "payments": [],
    "price": 22,
    "description": "✔ Simple and easy theme to use ✔ Well presented and convertible store and product page ✔ SEO optimized ✔ Responsive to all devices",
    "publicName": "Palest - Multipurpose Responsive E-commerce Template"
}